name: privacy_lookup
description: Privacy info lookup app by eri
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.3.0
  cached_network_image: ^3.3.1
  cryptography: ^2.7.0
  crypto: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ssl/arkhub_cert1.pem
    - assets/ssl/arkhub_cert2.pem
    - assets/ssl/thomelua_cert1.pem
    - assets/ssl/thomelua_cert2.pem
    - assets/ssl/sucyan.top_cert1.pem
    - assets/ssl/sucyan.top_cert2.pem
    - assets/ssl/ryapi.sbs_cert1.pem
    - assets/ssl/ryapi.sbs_cert2.pem
    - assets/ssl/api.ovo1.cc_cert1.pem
    - assets/ssl/api.ovo1.cc_cert2.pem
    - assets/ssl/arkhub_cert3.pem
    - assets/ssl/thomelua_cert3.pem
    - assets/ssl/sucyan.top_cert3.pem
    - assets/ssl/ryapi.sbs_cert3.pem
    - assets/ssl/api.ovo1.cc_cert3.pem